/*
 * This file is generated by jOOQ.
 */
package org.jooq.sources;


import javax.annotation.Generated;

import org.jooq.sources.tables.Mytable;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.mytable</code>.
     */
    public static final Mytable MYTABLE = org.jooq.sources.tables.Mytable.MYTABLE;
}
